"""
Downloader Module using yt-dlp.
Safely downloads single video streams into an isolated temp directory,
extracts video metadata, provides automatic ffmpeg thumbnail fallbacks,
supports custom referer/user-agent headers for protected streams,
and guarantees complete disk cleanup in all failure modes.
"""

import os
import stat
import shutil
import logging
import asyncio
import subprocess
from typing import Dict, Any, Optional, Tuple
import yt_dlp
from modules.crawler import is_preview_or_teaser

logger = logging.getLogger(__name__)

TEMP_DOWNLOAD_DIR = os.getenv("TEMP_DOWNLOAD_DIR", "temp_downloads")
DEFAULT_MIN_FREE_DISK_MB = int(os.getenv("MIN_FREE_DISK_MB", "500"))
DEFAULT_USER_AGENT = os.getenv(
    "USER_AGENT",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)
DEFAULT_REFERER = os.getenv("REFERER", None)


class VideoDownloader:
    """Handles single-item video downloads via yt-dlp with strict disk safety."""

    def __init__(
        self,
        download_dir: str = TEMP_DOWNLOAD_DIR,
        min_free_disk_mb: int = DEFAULT_MIN_FREE_DISK_MB,
        default_user_agent: Optional[str] = DEFAULT_USER_AGENT,
        default_referer: Optional[str] = DEFAULT_REFERER,
    ):
        self.download_dir = os.path.abspath(download_dir)
        self.min_free_bytes = max(0, min_free_disk_mb) * 1024 * 1024
        self.default_user_agent = default_user_agent
        self.default_referer = default_referer
        os.makedirs(self.download_dir, exist_ok=True)

    def check_disk_space(self, required_bytes: int = 0) -> Tuple[bool, int, Optional[str]]:
        """
        Pre-flight check to verify disk space before initiating download.
        Uses shutil.disk_usage on download directory.
        Returns: (has_sufficient_space, free_bytes, error_message_if_insufficient)
        """
        try:
            total, used, free = shutil.disk_usage(self.download_dir)
            min_required = max(self.min_free_bytes, required_bytes + self.min_free_bytes)
            if free < min_required:
                free_mb = free / (1024 * 1024)
                req_mb = min_required / (1024 * 1024)
                err = (
                    f"Pre-flight disk check failed: {free_mb:.1f} MB free disk space available on "
                    f"'{self.download_dir}', minimum required threshold is {req_mb:.1f} MB"
                )
                logger.error(err)
                return False, free, err
            return True, free, None
        except Exception as e:
            logger.warning(f"Unable to query disk usage for '{self.download_dir}': {e}")
            # Fallback: do not completely block execution if filesystem fails to report usage
            return True, 0, None

    def _get_ydl_opts(
        self,
        output_template: str,
        referer: Optional[str] = None,
        user_agent: Optional[str] = None,
        custom_headers: Optional[Dict[str, str]] = None
    ) -> Dict[str, Any]:
        """Generate optimized yt-dlp configuration with custom headers, referer, and user-agent support."""
        headers: Dict[str, str] = {}

        # Resolve User-Agent (argument -> class default -> env)
        resolved_ua = user_agent if user_agent is not None else self.default_user_agent
        if resolved_ua:
            headers["User-Agent"] = resolved_ua

        # Resolve Referer (argument -> class default -> env)
        resolved_referer = referer if referer is not None else self.default_referer
        if resolved_referer:
            headers["Referer"] = resolved_referer

        # Merge any additional custom headers
        if custom_headers:
            headers.update(custom_headers)

        opts: Dict[str, Any] = {
            "outtmpl": output_template,
            "format": "best[filesize<49M]/bestvideo[filesize<45M]+bestaudio/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
            "merge_output_format": "mp4",
            "noplaylist": True,
            "quiet": True,
            "no_warnings": True,
            "retries": 3,
            "fragment_retries": 3,
            "concurrent_fragment_downloads": 4,
            "continuedl": True,
            "socket_timeout": 30,
            "writethumbnail": True,
            "postprocessors": [
                {
                    "key": "FFmpegVideoConvertor",
                    "preferedformat": "mp4",
                }
            ],
        }

        if resolved_ua:
            opts["user_agent"] = resolved_ua
        if resolved_referer:
            opts["referer"] = resolved_referer
        if headers:
            opts["http_headers"] = headers

        return opts

    def _find_thumbnail(self, video_id: int) -> Optional[str]:
        """Locate any existing non-empty thumbnail generated by yt-dlp."""
        for ext in ("jpg", "jpeg", "webp", "png", ".jpg", ".jpeg", ".webp", ".png"):
            clean_ext = ext.lstrip(".")
            thumb_candidate = os.path.join(self.download_dir, f"video_{video_id}.{clean_ext}")
            if os.path.isfile(thumb_candidate) and os.path.getsize(thumb_candidate) > 0:
                return thumb_candidate
            thumb_candidate2 = os.path.join(self.download_dir, f"video_{video_id}_thumb.{clean_ext}")
            if os.path.isfile(thumb_candidate2) and os.path.getsize(thumb_candidate2) > 0:
                return thumb_candidate2
        return None

    def _generate_thumbnail_ffmpeg(
        self,
        video_path: str,
        video_id: int,
        duration: int = 0
    ) -> Optional[str]:
        """
        Generates a video thumbnail using ffmpeg fallback if yt-dlp did not produce one.
        Returns the absolute path to the generated thumbnail or None if generation failed.
        """
        if not video_path or not os.path.exists(video_path):
            return None

        ffmpeg_bin = shutil.which("ffmpeg")
        if not ffmpeg_bin:
            logger.warning("ffmpeg executable not found on PATH. Skipping automatic thumbnail generation.")
            return None

        thumb_output = os.path.join(self.download_dir, f"video_{video_id}.jpg")

        # Determine seek time: 10% of duration (capped at 5s), or fallback to 1s / 0s
        if duration > 2:
            seek_time = min(5.0, max(1.0, duration * 0.1))
        elif duration > 0:
            seek_time = max(0.0, duration / 2.0)
        else:
            seek_time = 0.0

        cmd = [
            ffmpeg_bin,
            "-y",
            "-ss", f"{seek_time:.2f}",
            "-i", video_path,
            "-vframes", "1",
            "-q:v", "2",
            "-f", "image2",
            thumb_output
        ]

        try:
            logger.info(f"Generating fallback thumbnail with ffmpeg at {seek_time:.2f}s for video {video_id}")
            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=30,
                check=False
            )

            # If seek failed, try fallback seeking from start (0s)
            if (result.returncode != 0 or not os.path.exists(thumb_output) or os.path.getsize(thumb_output) == 0) and seek_time > 0:
                logger.debug(f"Retrying ffmpeg thumbnail extraction at 0s for video {video_id}")
                cmd_fallback = [
                    ffmpeg_bin,
                    "-y",
                    "-ss", "00:00:00",
                    "-i", video_path,
                    "-vframes", "1",
                    "-q:v", "2",
                    "-f", "image2",
                    thumb_output
                ]
                subprocess.run(
                    cmd_fallback,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=30,
                    check=False
                )

            if os.path.isfile(thumb_output) and os.path.getsize(thumb_output) > 0:
                logger.info(f"Generated ffmpeg thumbnail: {thumb_output} ({os.path.getsize(thumb_output)} bytes)")
                return thumb_output

            # Remove 0-byte invalid file if left behind
            if os.path.exists(thumb_output):
                self.cleanup_file(thumb_output)
            return None

        except subprocess.TimeoutExpired:
            logger.warning(f"ffmpeg thumbnail generation timed out (30s) for video {video_id}")
            if os.path.exists(thumb_output):
                self.cleanup_file(thumb_output)
            return None
        except Exception as e:
            logger.warning(f"Failed to generate ffmpeg thumbnail for video {video_id}: {e}")
            if os.path.exists(thumb_output):
                self.cleanup_file(thumb_output)
            return None

    def _compress_video_for_telegram(
        self,
        video_path: str,
        video_id: int,
        duration: int,
        target_max_mb: float = 48.0
    ) -> Tuple[str, int]:
        """
        Compresses a video exceeding Telegram's 50MB Bot API limit using ffmpeg
        so it uploads successfully without HTTP 413 (Payload Too Large).
        Returns (path_to_video, file_size).
        """
        if not video_path or not os.path.exists(video_path):
            return video_path, 0

        current_size = os.path.getsize(video_path)
        max_bytes = int(target_max_mb * 1024 * 1024)
        if current_size <= max_bytes:
            return video_path, current_size

        ffmpeg_bin = shutil.which("ffmpeg")
        if not ffmpeg_bin:
            logger.warning(
                f"ffmpeg not available on PATH; cannot compress video {video_id} "
                f"({current_size / (1024*1024):.1f}MB > {target_max_mb}MB limit)."
            )
            return video_path, current_size

        eff_duration = duration if duration > 5 else 600
        # Calculate target video bitrate for 42MB target (guaranteed < 48MB with container overhead)
        safe_target_mb = min(target_max_mb, 42.0)
        safe_max_bytes = int(safe_target_mb * 1024 * 1024)
        total_bitrate_bps = int((safe_max_bytes * 8) / eff_duration)
        audio_bitrate_bps = 64000
        video_bitrate_bps = max(100000, total_bitrate_bps - audio_bitrate_bps)

        if video_bitrate_bps >= 450000:
            scale_filter = "scale='min(720,iw)':-2"
        elif video_bitrate_bps >= 250000:
            scale_filter = "scale='min(480,iw)':-2"
        else:
            scale_filter = "scale='min(360,iw)':-2"

        compressed_path = os.path.join(self.download_dir, f"video_{video_id}_tg50m.mp4")
        logger.info(
            f"Video {video_id} is {current_size / (1024*1024):.1f}MB (exceeds Telegram 50MB limit). "
            f"Auto-compressing via ffmpeg to ~{safe_target_mb}MB (bitrate: {video_bitrate_bps // 1000}kbps, scale: {scale_filter})..."
        )

        cmd = [
            ffmpeg_bin,
            "-y",
            "-i", video_path,
            "-c:v", "libx264",
            "-b:v", str(video_bitrate_bps),
            "-maxrate", str(video_bitrate_bps),
            "-bufsize", str(video_bitrate_bps),
            "-preset", "veryfast",
            "-vf", scale_filter,
            "-c:a", "aac",
            "-b:a", "64k",
            "-movflags", "+faststart",
            compressed_path
        ]

        try:
            res = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=400,
                check=False
            )
            if res.returncode == 0 and os.path.exists(compressed_path):
                compressed_size = os.path.getsize(compressed_path)
                # If still over 48.5MB, re-compress with reduced bitrate
                if compressed_size > 48.5 * 1024 * 1024:
                    logger.warning(
                        f"Compressed video {video_id} is {compressed_size / (1024*1024):.1f}MB (still > 48.5MB). "
                        "Applying aggressive second-pass compression..."
                    )
                    ratio = (40.0 * 1024 * 1024) / compressed_size
                    adjusted_bitrate = max(80000, int(video_bitrate_bps * ratio * 0.9))
                    temp_2nd = os.path.join(self.download_dir, f"video_{video_id}_tg50m_pass2.mp4")
                    cmd_2nd = [
                        ffmpeg_bin, "-y", "-i", compressed_path,
                        "-c:v", "libx264", "-b:v", str(adjusted_bitrate),
                        "-maxrate", str(adjusted_bitrate), "-bufsize", str(adjusted_bitrate),
                        "-preset", "veryfast", "-vf", "scale='min(480,iw)':-2",
                        "-c:a", "aac", "-b:a", "48k",
                        "-movflags", "+faststart", temp_2nd
                    ]
                    res2 = subprocess.run(cmd_2nd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=300, check=False)
                    if res2.returncode == 0 and os.path.exists(temp_2nd) and os.path.getsize(temp_2nd) > 0:
                        os.replace(temp_2nd, compressed_path)
                        compressed_size = os.path.getsize(compressed_path)

                if 0 < compressed_size <= 49.0 * 1024 * 1024:
                    logger.info(
                        f"Auto-compression succeeded for video {video_id}: "
                        f"{current_size / (1024*1024):.1f}MB -> {compressed_size / (1024*1024):.1f}MB (guaranteed Telegram compatible)"
                    )
                    try:
                        os.remove(video_path)
                    except Exception:
                        pass
                    return compressed_path, compressed_size

            stderr_snippet = res.stderr.decode("utf-8", errors="ignore")[-300:] if res.stderr else ""
            logger.error(f"ffmpeg compression returned code {res.returncode}: {stderr_snippet}")
        except Exception as e:
            logger.error(f"ffmpeg compression error for video {video_id}: {e}")

        return video_path, current_size

    async def download_video(
        self,
        video_id: int,
        url: str,
        referer: Optional[str] = None,
        user_agent: Optional[str] = None,
        custom_headers: Optional[Dict[str, str]] = None
    ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
        """
        Asynchronously downloads a video for the given queue item ID.
        Supports custom referer, user-agent, and extra HTTP headers for protected streams.
        Returns: (downloaded_file_path, metadata_dict, error_message)
        """
        loop = asyncio.get_running_loop()
        try:
            return await loop.run_in_executor(
                None,
                self._sync_download,
                video_id,
                url,
                referer,
                user_agent,
                custom_headers
            )
        except asyncio.CancelledError:
            logger.warning(f"Download task cancelled for video {video_id}. Wiping temporary files.")
            self.cleanup_video_files(video_id)
            raise
        except Exception as e:
            logger.error(f"Async executor error during download of video {video_id}: {e}")
            self.cleanup_video_files(video_id)
            return None, None, str(e)

    def _find_downloaded_file(self, video_id: int, ydl: Any, info: Dict[str, Any]) -> Optional[str]:
        """Locates the final downloaded video file on disk."""
        expected_mp4 = os.path.join(self.download_dir, f"video_{video_id}.mp4")
        if os.path.isfile(expected_mp4) and os.path.getsize(expected_mp4) > 0:
            return expected_mp4

        if info and "requested_downloads" in info:
            for req in info["requested_downloads"]:
                fp = req.get("filepath")
                if fp and os.path.isfile(fp) and os.path.getsize(fp) > 0:
                    return fp

        non_video_exts = (".jpg", ".jpeg", ".webp", ".png", ".part", ".ytdl", ".json", ".temp")
        dot_prefix = f"video_{video_id}."
        under_prefix = f"video_{video_id}_"

        if os.path.exists(self.download_dir):
            for fname in os.listdir(self.download_dir):
                if (fname.startswith(dot_prefix) or fname.startswith(under_prefix)) and not fname.endswith(non_video_exts):
                    candidate = os.path.join(self.download_dir, fname)
                    if os.path.isfile(candidate) and os.path.getsize(candidate) > 0:
                        return candidate

        return None

    def _sync_download(
        self,
        video_id: int,
        url: str,
        referer: Optional[str] = None,
        user_agent: Optional[str] = None,
        custom_headers: Optional[Dict[str, str]] = None
    ) -> Tuple[Optional[str], Optional[Dict[str, Any]], Optional[str]]:
        """
        Synchronous download execution routine.
        Performs pre-flight disk check, executes yt-dlp, resolves thumbnails,
        and guarantees strict cleanup on any failure.
        """
        # 1. Disk space pre-flight check
        has_space, free_bytes, space_err = self.check_disk_space()
        if not has_space:
            self.cleanup_video_files(video_id)
            return None, None, space_err

        # Auto-detect default origin referer if none was provided
        if not referer:
            try:
                from urllib.parse import urlparse
                p = urlparse(url)
                if p.scheme and p.netloc:
                    referer = f"{p.scheme}://{p.netloc}/"
            except Exception:
                pass

        output_template = os.path.join(self.download_dir, f"video_{video_id}.%(ext)s")
        expected_mp4 = os.path.join(self.download_dir, f"video_{video_id}.mp4")
        ydl_opts = self._get_ydl_opts(
            output_template=output_template,
            referer=referer,
            user_agent=user_agent,
            custom_headers=custom_headers
        )

        metadata = {
            "title": "",
            "duration": 0,
            "width": 0,
            "height": 0,
            "thumbnail": None,
            "file_size": 0
        }

        download_success = False
        target_file = None

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                logger.info(f"Extracting info and downloading: {url} (Referer: {referer})")
                info = ydl.extract_info(url, download=True)
                if not info:
                    self.cleanup_video_files(video_id)
                    return None, None, "yt-dlp returned empty info dictionary"

                # Extract metadata
                metadata["title"] = info.get("title") or ""
                metadata["duration"] = int(info.get("duration") or 0)
                metadata["width"] = int(info.get("width") or 0)
                metadata["height"] = int(info.get("height") or 0)

                # Locate downloaded file
                target_file = self._find_downloaded_file(video_id, ydl, info)
                if not target_file or not os.path.exists(target_file):
                    self.cleanup_video_files(video_id)
                    return None, None, "Downloaded file not found on disk"

                file_size = os.path.getsize(target_file)
                metadata["file_size"] = file_size

                # Strict validation against 3-5s teaser/hover preview files
                if 0 < metadata["duration"] <= 10 and file_size < 3 * 1024 * 1024:
                    if is_preview_or_teaser(url, metadata.get("title", "")):
                        logger.warning(f"Video {video_id} is a short preview/teaser clip ({metadata['duration']}s, {file_size} bytes). Discarding.")
                        self.cleanup_video_files(video_id)
                        return None, None, f"Rejected short teaser clip (duration: {metadata['duration']}s, size: {file_size} bytes)"

                # 2. Check for thumbnail produced by yt-dlp
                thumb_path = self._find_thumbnail(video_id)

                # 3. Fallback: automatic ffmpeg thumbnail generation if missing
                if not thumb_path:
                    thumb_path = self._generate_thumbnail_ffmpeg(
                        video_path=target_file,
                        video_id=video_id,
                        duration=metadata["duration"]
                    )

                metadata["thumbnail"] = thumb_path

                # 4. Auto-compress if file exceeds Telegram's standard 50MB Bot API limit
                if file_size > 49 * 1024 * 1024:
                    target_file, file_size = self._compress_video_for_telegram(
                        video_path=target_file,
                        video_id=video_id,
                        duration=metadata["duration"],
                        target_max_mb=48.0
                    )
                    metadata["file_size"] = file_size

                download_success = True
                logger.info(f"Downloaded video {video_id}: {target_file} ({file_size / (1024*1024):.2f} MB)")
                return target_file, metadata, None

        except Exception as e:
            error_msg = str(e)
            logger.error(f"Failed to download video {video_id} from {url}: {error_msg}")
            return None, None, error_msg
        finally:
            # Strictly wipe clean all temporary files matching video_{video_id}.* in all failure modes
            if not download_success:
                self.cleanup_video_files(video_id)

    def cleanup_video_files(self, video_id: int) -> None:
        """
        Removes all temporary files associated with a given video ID
        (video streams, audio parts, fragment caches, thumbnails, info json, ytdl temp files).
        Matches patterns: video_{id}.*, video_{id}_*, and exact video_{id}.
        """
        if not os.path.exists(self.download_dir):
            return

        str_id = str(video_id)
        dot_prefix = f"video_{str_id}."
        under_prefix = f"video_{str_id}_"
        exact_name = f"video_{str_id}"

        try:
            for fname in os.listdir(self.download_dir):
                if fname.startswith(dot_prefix) or fname.startswith(under_prefix) or fname == exact_name:
                    fpath = os.path.join(self.download_dir, fname)
                    self.cleanup_file(fpath)
        except Exception as e:
            logger.error(f"Error scanning temp directory '{self.download_dir}' for cleanup of video {video_id}: {e}")

    @staticmethod
    def cleanup_file(file_path: Optional[str]) -> None:
        """Safely delete a single file or directory if it exists, handling read-only permissions."""
        if not file_path:
            return
        try:
            if os.path.islink(file_path) or os.path.isfile(file_path):
                # Ensure write permission before removal on Windows/POSIX
                try:
                    os.chmod(file_path, stat.S_IWRITE | stat.S_IREAD)
                except Exception:
                    pass
                os.remove(file_path)
                logger.debug(f"Removed temp file: {file_path}")
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path, ignore_errors=True)
                logger.debug(f"Removed temp directory: {file_path}")
        except Exception as e:
            logger.warning(f"Failed to delete {file_path}: {e}")

    def purge_all_temp(self) -> None:
        """Cleans entire temp download folder on startup to ensure zero disk leftovers."""
        if os.path.exists(self.download_dir):
            try:
                for item in os.listdir(self.download_dir):
                    item_path = os.path.join(self.download_dir, item)
                    self.cleanup_file(item_path)
                logger.info(f"Purged temporary download directory: {self.download_dir}")
            except Exception as e:
                logger.warning(f"Could not purge temp directory '{self.download_dir}': {e}")
        else:
            os.makedirs(self.download_dir, exist_ok=True)


# Global downloader instance
downloader = VideoDownloader()
